version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: conduitpass
      POSTGRES_DB: conduitdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ConduitLLM.Http/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_PROVIDER: postgres
      DB_CONNECTION_STRING: Host=postgres;Port=5432;Database=conduitdb;Username=conduit;Password=conduitpass
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5000:8080"

  webui:
    build:
      context: .
      dockerfile: ConduitLLM.WebUI/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_PROVIDER: postgres
      DB_CONNECTION_STRING: Host=postgres;Port=5432;Database=conduitdb;Username=conduit;Password=conduitpass
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5001:8080"

volumes:
  pgdata:
