# Development docker-compose with volume mounts for hot reloading
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  webui:
    # Remove user override to use default container user
    volumes:
      # Mount source code for hot reloading
      - ./ConduitLLM.WebUI:/app/ConduitLLM.WebUI:delegated
      - ./SDKs/Node/Admin:/app/SDKs/Node/Admin:delegated
      - ./SDKs/Node/Core:/app/SDKs/Node/Core:delegated
      # Prevent node_modules from being overwritten
      - /app/ConduitLLM.WebUI/node_modules
      - /app/SDKs/Node/Admin/node_modules
      - /app/SDKs/Node/Core/node_modules
    environment:
      # Enable Next.js development mode
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      # Enhanced hot reload settings
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      # Fast refresh
      FAST_REFRESH: "true"
    working_dir: /app/ConduitLLM.WebUI
    # Start dev server directly, assuming dependencies are already installed
    command: npm run dev