# Development docker-compose with volume mounts for hot reloading
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  webui:
    # Override user to root in development to avoid permission issues
    user: root
    volumes:
      # Mount source code for hot reloading
      - ./ConduitLLM.WebUI:/app/ConduitLLM.WebUI:delegated
      - ./Clients/Node/Admin:/app/Clients/Node/Admin:delegated
      - ./Clients/Node/Core:/app/Clients/Node/Core:delegated
      # Prevent node_modules from being overwritten
      - /app/ConduitLLM.WebUI/node_modules
      - /app/Clients/Node/Admin/node_modules
      - /app/Clients/Node/Core/node_modules
    environment:
      # Enable Next.js development mode
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      # Enhanced hot reload settings
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
      # Fast refresh
      FAST_REFRESH: "true"
    working_dir: /app/ConduitLLM.WebUI
    # HACKY FIX: Build SDKs and install deps before starting
    command: sh -c "cd /app/Clients/Node/Admin && npm run build && cd /app/Clients/Node/Core && npm run build && cd /app/ConduitLLM.WebUI && npm install && npm run dev"