apiVersion: 1

contactPoints:
  - orgId: 1
    name: conduit-oncall
    receivers:
      - uid: conduit-oncall-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: $CONDUIT_ALERT_WEBHOOK_URL
          httpMethod: POST

policies:
  - orgId: 1
    receiver: conduit-oncall
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
