using ConfigDto = ConduitLLM.Configuration.Services.Dtos;

namespace ConduitLLM.WebUI.DTOs
{
    /// <summary>
    /// Type alias for the RequestsByModelDto from ConduitLLM.Configuration.Services.Dtos
    /// This exists to maintain backward compatibility while consolidating duplicate definitions.
    /// </summary>
    public class RequestsByModelDto : ConfigDto.RequestsByModelDto
    {
        /// <summary>
        /// Input tokens processed by this model (WebUI-specific property)
        /// </summary>
        public int InputTokens { get; set; }

        /// <summary>
        /// Output tokens generated by this model (WebUI-specific property)
        /// </summary>
        public int OutputTokens { get; set; }

        /// <summary>
        /// Average response time in milliseconds (WebUI-specific property)
        /// </summary>
        public double AverageResponseTimeMs { get; set; }
    }
}
