namespace ConduitLLM.WebUI.DTOs
{
    /// <summary>
    /// Request statistics aggregated by model
    /// </summary>
    public class RequestsByModelDto
    {
        /// <summary>
        /// Name of the model
        /// </summary>
        public string ModelName { get; set; } = string.Empty;

        /// <summary>
        /// Number of requests to this model
        /// </summary>
        public int RequestCount { get; set; }

        /// <summary>
        /// Cost associated with this model
        /// </summary>
        public decimal Cost { get; set; }

        /// <summary>
        /// Input tokens processed by this model
        /// </summary>
        public int InputTokens { get; set; }

        /// <summary>
        /// Output tokens generated by this model
        /// </summary>
        public int OutputTokens { get; set; }

        /// <summary>
        /// Average response time in milliseconds
        /// </summary>
        public double AverageResponseTimeMs { get; set; }
    }
}