import {
  IconDashboard,
  IconKey,
  IconServer,
  IconMessageChatbot,
  IconPhoto,
  IconVideo,
  IconMicrophone,
  IconSettings,
  IconChartBar,
  IconUsers,
  IconShield,
  IconShield as IconHealth,
  IconDatabase,
  IconRoute,
  IconCloud,
  IconActivity,
  IconFileText,
  IconCreditCard,
  IconNetwork,
  IconFilter,
  IconDeviceDesktop,
} from '@tabler/icons-react';
import { NavigationSection } from '@/types/navigation';

export const navigationSections: NavigationSection[] = [
  {
    id: 'main',
    label: 'Main',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        icon: IconDashboard,
        href: '/',
        description: 'Overview and quick access',
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    items: [
      {
        id: 'chat',
        label: 'Chat Interface',
        icon: IconMessageChatbot,
        href: '/chat',
        description: 'Test LLM models with interactive chat',
        color: 'blue',
      },
      {
        id: 'image-generation',
        label: 'Image Generation',
        icon: IconPhoto,
        href: '/image-generation',
        description: 'Generate images with AI',
        color: 'pink',
      },
      {
        id: 'video-generation',
        label: 'Video Generation',
        icon: IconVideo,
        href: '/video-generation',
        description: 'Create videos with AI',
        color: 'red',
      },
      {
        id: 'audio-test',
        label: 'Audio Processing',
        icon: IconMicrophone,
        href: '/audio-test',
        description: 'Transcription, translation, and TTS',
        color: 'teal',
      },
    ],
  },
  {
    id: 'configuration',
    label: 'Configuration',
    items: [
      {
        id: 'llm-providers',
        label: 'LLM Providers',
        icon: IconServer,
        href: '/llm-providers',
        description: 'Manage LLM provider credentials',
        color: 'purple',
      },
      {
        id: 'audio-providers',
        label: 'Audio Providers',
        icon: IconCloud,
        href: '/audio-providers',
        description: 'Configure audio service providers',
        color: 'cyan',
      },
      {
        id: 'model-mappings',
        label: 'Model Mappings',
        icon: IconRoute,
        href: '/model-mappings',
        description: 'Configure model routing',
        color: 'indigo',
      },
      {
        id: 'configuration',
        label: 'General Settings',
        icon: IconSettings,
        href: '/configuration',
        description: 'System configuration',
        color: 'gray',
      },
      {
        id: 'routing-settings',
        label: 'Routing Settings',
        icon: IconNetwork,
        href: '/routing-settings',
        description: 'Configure request routing',
      },
      {
        id: 'caching-settings',
        label: 'Caching Settings',
        icon: IconDatabase,
        href: '/caching-settings',
        description: 'Cache configuration',
      },
      {
        id: 'ip-filtering',
        label: 'IP Filtering',
        icon: IconFilter,
        href: '/ip-filtering',
        description: 'Access control and filtering',
      },
      {
        id: 'security',
        label: 'Security Dashboard',
        icon: IconShield,
        href: '/security',
        description: 'Security monitoring and alerts',
      },
    ],
  },
  {
    id: 'keys-analytics',
    label: 'Keys & Analytics',
    items: [
      {
        id: 'virtualkeys',
        label: 'Virtual Keys',
        icon: IconKey,
        href: '/virtualkeys',
        description: 'Manage API keys and budgets',
        color: 'green',
      },
      {
        id: 'virtualkeys-dashboard',
        label: 'Keys Dashboard',
        icon: IconUsers,
        href: '/virtualkeys/dashboard',
        description: 'Virtual keys overview',
      },
      {
        id: 'media',
        label: 'Media Assets',
        icon: IconPhoto,
        href: '/media',
        description: 'Generated media files',
      },
      {
        id: 'cost-dashboard',
        label: 'Cost Analytics',
        icon: IconCreditCard,
        href: '/cost-dashboard',
        description: 'Usage costs and analytics',
        color: 'orange',
      },
      {
        id: 'usage-analytics',
        label: 'Usage Analytics',
        icon: IconActivity,
        href: '/usage-analytics',
        description: 'API usage and performance metrics',
        color: 'blue',
      },
      {
        id: 'virtual-keys-analytics',
        label: 'Virtual Keys Analytics',
        icon: IconKey,
        href: '/virtual-keys-analytics',
        description: 'Comprehensive virtual key analytics and monitoring',
        color: 'purple',
      },
      {
        id: 'request-logs',
        label: 'Request Logs',
        icon: IconFileText,
        href: '/request-logs',
        description: 'API request history',
      },
      {
        id: 'model-costs',
        label: 'Model Pricing',
        icon: IconCreditCard,
        href: '/model-costs',
        description: 'Model cost configuration',
      },
      {
        id: 'audio-usage',
        label: 'Audio Usage',
        icon: IconMicrophone,
        href: '/audio-usage',
        description: 'Audio processing analytics',
      },
    ],
  },
  {
    id: 'system',
    label: 'System Health',
    items: [
      {
        id: 'system-info',
        label: 'System Information',
        icon: IconDeviceDesktop,
        href: '/system-info',
        description: 'System status and information',
      },
      {
        id: 'provider-health',
        label: 'Provider Health',
        icon: IconHealth,
        href: '/provider-health',
        description: 'Monitor provider status',
      },
      {
        id: 'metrics-dashboard',
        label: 'Metrics Dashboard',
        icon: IconActivity,
        href: '/metrics-dashboard',
        description: 'Performance metrics',
      },
      {
        id: 'health-monitoring',
        label: 'Health Monitoring',
        icon: IconHealth,
        href: '/health-monitoring',
        description: 'System health checks',
      },
      {
        id: 'security-monitoring',
        label: 'Security Monitoring',
        icon: IconShield,
        href: '/security-monitoring',
        description: 'Security event monitoring',
      },
    ],
  },
];