import {
  IconDashboard,
  IconKey,
  IconServer,
  IconMessageChatbot,
  IconPhoto,
  IconVideo,
  IconShield,
  IconShield as IconHealth,
  IconRoute,
  IconActivity,
  IconCreditCard,
  IconNetwork,
  IconFilter,
  IconDeviceDesktop,
  IconEye,
  IconBrain,
  IconAlertCircle,
} from '@tabler/icons-react';
import { NavigationSection } from '@/types/navigation';

export const navigationSections: NavigationSection[] = [
  {
    id: 'main',
    label: 'Main',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        icon: IconDashboard,
        href: '/',
        description: 'Overview and quick access',
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    items: [
      {
        id: 'chat',
        label: 'Chat Interface',
        icon: IconMessageChatbot,
        href: '/chat',
        description: 'Test LLM models with interactive chat',
        color: 'blue',
      },
      {
        id: 'image-generation',
        label: 'Image Generation',
        icon: IconPhoto,
        href: '/images',
        description: 'Generate images with AI',
        color: 'pink',
      },
      {
        id: 'video-generation',
        label: 'Video Generation',
        icon: IconVideo,
        href: '/video-generation',
        description: 'Create videos with AI',
        color: 'red',
      },
    ],
  },
  {
    id: 'configuration',
    label: 'Configuration',
    items: [
      {
        id: 'llm-providers',
        label: 'LLM Providers',
        icon: IconServer,
        href: '/llm-providers',
        description: 'Manage LLM provider credentials',
        color: 'purple',
      },
      {
        id: 'models',
        label: 'Models',
        icon: IconBrain,
        href: '/models',
        description: 'Manage AI models and capabilities',
        color: 'violet',
      },
      {
        id: 'model-mappings',
        label: 'Model Mappings',
        icon: IconRoute,
        href: '/model-mappings',
        description: 'Configure model routing',
        color: 'indigo',
      },
      {
        id: 'routing-settings',
        label: 'Routing Settings',
        icon: IconNetwork,
        href: '/routing-settings',
        description: 'Configure request routing',
      },
      {
        id: 'ip-filtering',
        label: 'IP Filtering',
        icon: IconFilter,
        href: '/ip-filtering',
        description: 'Access control and filtering',
      },
      {
        id: 'security',
        label: 'Security Dashboard',
        icon: IconShield,
        href: '/security',
        description: 'Security monitoring and alerts',
      },
    ],
  },
  {
    id: 'keys-analytics',
    label: 'Keys & Analytics',
    items: [
      {
        id: 'virtualkeys',
        label: 'Virtual Keys',
        icon: IconKey,
        href: '/virtualkeys',
        description: 'Manage API keys and budgets',
        color: 'green',
      },
      {
        id: 'virtualkeys-discovery-preview',
        label: 'Discovery Preview',
        icon: IconEye,
        href: '/virtualkeys/discovery-preview',
        description: 'Preview model discovery for virtual keys',
        color: 'teal',
      },
      {
        id: 'media',
        label: 'Media Assets',
        icon: IconPhoto,
        href: '/media',
        description: 'Generated media files',
      },
      {
        id: 'cost-dashboard',
        label: 'Cost Analytics',
        icon: IconCreditCard,
        href: '/cost-dashboard',
        description: 'Usage costs and analytics',
        color: 'orange',
      },
      {
        id: 'usage-analytics',
        label: 'Usage Analytics',
        icon: IconActivity,
        href: '/usage-analytics',
        description: 'API usage and performance metrics',
        color: 'blue',
      },
      {
        id: 'model-costs',
        label: 'Model Pricing',
        icon: IconCreditCard,
        href: '/model-costs',
        description: 'Model cost configuration',
      },
    ],
  },
  {
    id: 'system',
    label: 'System Health',
    items: [
      {
        id: 'system-info',
        label: 'System Information',
        icon: IconDeviceDesktop,
        href: '/system-info',
        description: 'System status and information',
      },
      {
        id: 'provider-health',
        label: 'Provider Health',
        icon: IconHealth,
        href: '/provider-health',
        description: 'Monitor provider status',
      },
      {
        id: 'provider-errors',
        label: 'Provider Errors',
        icon: IconAlertCircle,
        href: '/provider-errors',
        description: 'Monitor and manage provider errors',
        color: 'red',
      },
      {
        id: 'security-monitoring',
        label: 'Security Monitoring',
        icon: IconShield,
        href: '/security-monitoring',
        description: 'Security event monitoring',
      },
    ],
  },
];