using System.Globalization;

using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Interfaces;
using ConduitLLM.Persistence.Npgsql;

using Npgsql;

var configured = Environment.GetEnvironmentVariable("DATABASE_URL");
if (string.IsNullOrWhiteSpace(configured))
{
    Console.Error.WriteLine("DATABASE_URL is required.");
    return 2;
}

var connectionString = NormalizeConnectionString(configured);
var schema = $"conduit_aot_probe_{Guid.NewGuid():N}";

try
{
    await using var connection = new NpgsqlConnection(connectionString);
    await OpenWithRetryAsync(connection);
    await ExecuteAsync(connection, $"""
        CREATE SCHEMA "{schema}";
        CREATE TABLE "{schema}".records (
            id uuid PRIMARY KEY,
            version bigint NOT NULL,
            amount numeric(18,6) NOT NULL,
            payload jsonb NOT NULL,
            created_at timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."GlobalSettings" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Key" character varying(100) NOT NULL UNIQUE,
            "Value" character varying(2000) NOT NULL,
            "Description" character varying(500) NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."VirtualKeys" (
            "Id" integer PRIMARY KEY
        );
        INSERT INTO "{schema}"."VirtualKeys" ("Id") VALUES (41), (42);
        CREATE TABLE "{schema}"."IpFilters" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FilterType" character varying(10) NOT NULL,
            "IpAddressOrCidr" character varying(50) NOT NULL,
            "Name" character varying(100) NULL,
            "Description" character varying(500) NULL,
            "IsEnabled" boolean NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "CreatedBy" character varying(100) NULL,
            "UpdatedBy" character varying(100) NULL,
            "VirtualKeyId" integer NULL REFERENCES "{schema}"."VirtualKeys" ("Id") ON DELETE CASCADE,
            "RowVersion" bytea NULL
        );
        """);

    var id = Guid.NewGuid();
    var createdAt = DateTimeOffset.UtcNow;
    await using (var insert = new NpgsqlCommand(
        $"INSERT INTO \"{schema}\".records VALUES (@id, 0, @amount, @payload::jsonb, @created)", connection))
    {
        insert.Parameters.AddWithValue("id", id);
        insert.Parameters.AddWithValue("amount", 12.345678m);
        insert.Parameters.AddWithValue("payload", "{\"kind\":\"native\"}");
        insert.Parameters.AddWithValue("created", createdAt);
        Ensure(await insert.ExecuteNonQueryAsync() == 1, "write failed");
    }

    await using (var read = new NpgsqlCommand(
        $"SELECT amount, payload->>'kind', created_at FROM \"{schema}\".records WHERE id=@id", connection))
    {
        read.Parameters.AddWithValue("id", id);
        await using var reader = await read.ExecuteReaderAsync();
        Ensure(await reader.ReadAsync(), "read failed");
        Ensure(reader.GetDecimal(0) == 12.345678m, "numeric mapping failed");
        Ensure(reader.GetString(1) == "native", "jsonb mapping failed");
        Ensure(reader.GetFieldValue<DateTime>(2).Kind == DateTimeKind.Utc, "timestamptz mapping failed");
    }

    await using (var transaction = await connection.BeginTransactionAsync())
    {
        await using var rolledBack = new NpgsqlCommand(
            $"INSERT INTO \"{schema}\".records VALUES (@id, 0, 1, '{{}}', now())", connection, transaction);
        rolledBack.Parameters.AddWithValue("id", Guid.NewGuid());
        await rolledBack.ExecuteNonQueryAsync();
        await transaction.RollbackAsync();
    }
    Ensure(await ScalarAsync<long>(connection, $"SELECT count(*) FROM \"{schema}\".records") == 1, "rollback failed");

    var updates = await Task.WhenAll(
        TryOptimisticUpdateAsync(connectionString, schema, id),
        TryOptimisticUpdateAsync(connectionString, schema, id));
    Ensure(updates.Sum() == 1, "optimistic concurrency failed");

    var attempts = 0;
    await RetrySerializationAsync(async () =>
    {
        attempts++;
        if (attempts == 1)
        {
            await ExecuteAsync(connection, "SET SESSION application_name = 'conduit-aot-retry-ready'");
            await ExecuteAsync(connection, "DO $$ BEGIN RAISE EXCEPTION 'retry probe' USING ERRCODE='40001'; END $$;");
        }
        return await ScalarAsync<int>(connection, "SELECT 1");
    });
    Ensure(attempts == 2, "serialization retry failed");

    var storeConnectionString = new NpgsqlConnectionStringBuilder(connectionString)
    {
        SearchPath = schema
    }.ConnectionString;
    await using (var dataSource = NpgsqlDataSource.Create(storeConnectionString))
    {
        await ExerciseGlobalSettingRepositoryAsync(new NpgsqlGlobalSettingRepository(dataSource));
        await ExerciseIpFilterRepositoryAsync(new NpgsqlIpFilterRepository(dataSource));
    }

    Console.WriteLine("Native persistence probe passed: reads, writes, rollback, concurrency, retry, PostgreSQL mappings, and the global-settings and IP-filter repositories.");
    return 0;
}
finally
{
    try
    {
        await using var cleanup = new NpgsqlConnection(connectionString);
        await cleanup.OpenAsync();
        await ExecuteAsync(cleanup, $"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE");
    }
    catch (Exception exception)
    {
        Console.Error.WriteLine($"Cleanup failed: {exception.Message}");
    }
}

static string NormalizeConnectionString(string configured)
{
    if (!Uri.TryCreate(configured, UriKind.Absolute, out var uri) ||
        (uri.Scheme != "postgres" && uri.Scheme != "postgresql"))
    {
        return configured;
    }

    var credentials = uri.UserInfo.Split(':', 2);
    return new NpgsqlConnectionStringBuilder
    {
        Host = uri.Host,
        Port = uri.IsDefaultPort ? 5432 : uri.Port,
        Database = uri.AbsolutePath.TrimStart('/'),
        Username = Uri.UnescapeDataString(credentials[0]),
        Password = credentials.Length == 2 ? Uri.UnescapeDataString(credentials[1]) : string.Empty
    }.ConnectionString;
}

static async Task OpenWithRetryAsync(NpgsqlConnection connection)
{
    for (var attempt = 1; ; attempt++)
    {
        try
        {
            await connection.OpenAsync();
            return;
        }
        catch (NpgsqlException) when (attempt < 4)
        {
            await Task.Delay(TimeSpan.FromMilliseconds(100 * attempt));
        }
    }
}

static async Task<int> TryOptimisticUpdateAsync(string connectionString, string schema, Guid id)
{
    await using var connection = new NpgsqlConnection(connectionString);
    await connection.OpenAsync();
    await using var command = new NpgsqlCommand(
        $"UPDATE \"{schema}\".records SET version=version+1 WHERE id=@id AND version=0", connection);
    command.Parameters.AddWithValue("id", id);
    return await command.ExecuteNonQueryAsync();
}

static async Task<T> RetrySerializationAsync<T>(Func<Task<T>> operation)
{
    for (var attempt = 1; ; attempt++)
    {
        try
        {
            return await operation();
        }
        catch (PostgresException exception) when (exception.SqlState == "40001" && attempt < 3)
        {
            await Task.Delay(TimeSpan.FromMilliseconds(25 * attempt));
        }
    }
}

static async Task ExecuteAsync(NpgsqlConnection connection, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection);
    await command.ExecuteNonQueryAsync();
}

static async Task<T> ScalarAsync<T>(NpgsqlConnection connection, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection);
    var value = await command.ExecuteScalarAsync();
    return (T)Convert.ChangeType(value!, typeof(T), CultureInfo.InvariantCulture);
}

static async Task ExerciseGlobalSettingRepositoryAsync(IGlobalSettingRepository repository)
{
    Ensure((await repository.ListAsync()).Count == 0, "global-settings initial list failed");

    var setting = new GlobalSetting
    {
        Key = "native.probe",
        Value = "one",
        Description = "initial",
        CreatedAt = default
    };
    var id = await repository.CreateAsync(setting);
    Ensure(id > 0 && setting.Id == id, "global-settings create failed");

    var byId = await repository.GetByIdAsync(id)
        ?? throw new InvalidOperationException("global-settings ID lookup failed");
    Ensure(byId.Key == setting.Key, "global-settings ID lookup failed");
    Ensure(byId.CreatedAt.Kind == DateTimeKind.Utc, "global-settings UTC mapping failed");

    byId.Value = "two";
    byId.Description = null;
    Ensure(await repository.UpdateAsync(byId), "global-settings update failed");
    Ensure((await repository.GetByKeyAsync(setting.Key))?.Description is null,
        "global-settings nullable mapping failed");

    Ensure(await repository.UpsertAsync(setting.Key, "three", "restored"),
        "global-settings update upsert failed");
    Ensure(await repository.UpsertAsync(setting.Key, "four"),
        "global-settings description-preserving upsert failed");
    var afterUpsert = await repository.GetByKeyAsync(setting.Key);
    Ensure(afterUpsert is { Value: "four", Description: "restored" },
        "global-settings upsert semantics failed");

    Ensure(await repository.UpsertAsync("native.alpha", "first"),
        "global-settings insert upsert failed");
    var settings = await repository.ListAsync();
    Ensure(settings.Count == 2 && settings[0].Key == "native.alpha" && settings[1].Key == setting.Key,
        "global-settings ordered list failed");

    Ensure(await repository.DeleteAsync(id), "global-settings ID delete failed");
    Ensure(await repository.DeleteByKeyAsync("native.alpha"), "global-settings key delete failed");
    Ensure((await repository.ListAsync()).Count == 0, "global-settings cleanup failed");
}

static async Task ExerciseIpFilterRepositoryAsync(IIpFilterRepository repository)
{
    Ensure((await repository.ListAsync()).Count == 0, "IP-filter initial list failed");

    var global = await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "blacklist",
        IpAddressOrCidr = "10.0.0.0/8",
        Name = "native global",
        IsEnabled = true,
        CreatedAt = default
    });
    var keyRule = await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "whitelist",
        IpAddressOrCidr = "192.0.2.0/24",
        Description = "native per-key",
        IsEnabled = true,
        VirtualKeyId = 41
    });
    await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "blacklist",
        IpAddressOrCidr = "198.51.100.0/24",
        IsEnabled = false,
        VirtualKeyId = 42
    });

    Ensure(global.Id > 0 && keyRule.Id > 0, "IP-filter create failed");
    Ensure(global.CreatedAt.Kind == DateTimeKind.Utc, "IP-filter UTC mapping failed");
    Ensure((await repository.GetEnabledAsync()).Count == 1, "IP-filter global scope failed");
    Ensure((await repository.GetEnabledPerKeyAsync()).Count == 1, "IP-filter per-key scope failed");
    Ensure((await repository.GetByVirtualKeyIdAsync(42)).Count == 1, "IP-filter key lookup failed");

    var byId = await repository.GetByIdAsync(global.Id)
        ?? throw new InvalidOperationException("IP-filter ID lookup failed");
    byId.Name = "updated native global";
    byId.Description = null;
    Ensure(await repository.UpdateAsync(byId), "IP-filter update failed");
    Ensure((await repository.GetByIdAsync(global.Id))?.Name == "updated native global",
        "IP-filter updated value lookup failed");

    foreach (var filter in await repository.ListAsync())
    {
        Ensure(await repository.DeleteAsync(filter.Id), "IP-filter delete failed");
    }

    Ensure((await repository.ListAsync()).Count == 0, "IP-filter cleanup failed");
}

static void Ensure(bool condition, string message)
{
    if (!condition)
    {
        throw new InvalidOperationException(message);
    }
}
