apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "10s"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: conduit
    database: conduitdb
    editable: true
    secureJsonData:
      password: conduitpass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: false