# Integration Test Configuration - Auto-detected from docker-compose.dev.yml

environment:
  coreApiUrl: "http://localhost:5000"
  adminApiUrl: "http://localhost:5002"
  # All other settings auto-detected from docker-compose.dev.yml
  
  timeouts:
    default: 10
    chat: 60
    imageGen: 120
    videoGen: 300

# Test defaults
defaults:
  virtualKeyCredit: 100.00  # $100 per test run
  testPrefix: "TEST_"       # Prefix for all created entities

# Active providers for testing (add provider config files to Config/providers/)
activeProviders:
  - groq
  # Add more providers as testing expands:
  # - openai
  # - anthropic
  # - cerebras
  # - sambanova