using ConduitLLM.Admin.Interfaces;
using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Enums;
using ConduitLLM.Configuration.Interfaces;
using ConduitLLM.Core.Interfaces;
using ConduitLLM.Core.Models;
using Microsoft.Extensions.Logging;

namespace ConduitLLM.Admin.Services;

/// <summary>
/// Service for processing refunds for virtual key group usage
/// </summary>
public class RefundService : IRefundService
{
    private readonly ICostCalculationService _costCalculationService;
    private readonly IVirtualKeyGroupRepository _groupRepository;
    private readonly IConfigurationDbContext _context;
    private readonly ILogger<RefundService> _logger;

    /// <summary>
    /// Initializes a new instance of the RefundService
    /// </summary>
    public RefundService(
        ICostCalculationService costCalculationService,
        IVirtualKeyGroupRepository groupRepository,
        IConfigurationDbContext context,
        ILogger<RefundService> logger)
    {
        _costCalculationService = costCalculationService;
        _groupRepository = groupRepository;
        _context = context;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task<RefundResult> ProcessRefundAsync(
        int virtualKeyGroupId,
        string modelId,
        Usage originalUsage,
        Usage refundUsage,
        string refundReason,
        string? originalTransactionId,
        string initiatedBy,
        string? initiatedByUserId,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation(
            "Processing refund for group {GroupId}, model {ModelId}, initiated by {InitiatedBy}",
            virtualKeyGroupId, modelId, initiatedBy);

        // Validate group exists
        var group = await _groupRepository.GetByIdAsync(virtualKeyGroupId);
        if (group == null)
        {
            _logger.LogWarning("Refund rejected: virtual key group {GroupId} not found", virtualKeyGroupId);
            throw new InvalidOperationException($"Virtual key group {virtualKeyGroupId} not found");
        }

        // Calculate refund using the cost calculation service
        var refundResult = await _costCalculationService.CalculateRefundAsync(
            modelId,
            originalUsage,
            refundUsage,
            refundReason,
            originalTransactionId,
            cancellationToken);

        // Check for validation errors
        if (refundResult.ValidationMessages.Count > 0 && refundResult.RefundAmount == 0)
        {
            var errorMessage = string.Join("; ", refundResult.ValidationMessages);
            _logger.LogWarning(
                "Refund validation failed for group {GroupId}, model {ModelId}: {ValidationErrors}",
                virtualKeyGroupId, modelId, errorMessage);
            throw new ArgumentException($"Refund validation failed: {errorMessage}");
        }

        // Update group balance
        var previousBalance = group.Balance;
        group.Balance += refundResult.RefundAmount; // Refunds are always positive, so we add
        group.UpdatedAt = DateTime.UtcNow;

        // Create transaction record with Refund type
        var transaction = new VirtualKeyGroupTransaction
        {
            VirtualKeyGroupId = virtualKeyGroupId,
            TransactionType = TransactionType.Refund,
            Amount = refundResult.RefundAmount, // Always positive
            BalanceAfter = group.Balance,
            ReferenceType = ReferenceType.Manual, // Refunds are manual administrative actions
            ReferenceId = originalTransactionId,
            Description = $"Refund: {refundReason} (Model: {modelId})",
            InitiatedBy = initiatedBy,
            InitiatedByUserId = initiatedByUserId,
            CreatedAt = DateTime.UtcNow
        };

        // Attach and update the group entity (it was fetched with AsNoTracking)
        _context.VirtualKeyGroups.Update(group);
        _context.VirtualKeyGroupTransactions.Add(transaction);
        await _context.SaveChangesAsync(cancellationToken);

        // Update the refund result with the transaction ID
        // Note: The transaction ID is generated by the database after SaveChangesAsync
        refundResult.OriginalTransactionId = transaction.Id.ToString();

        _logger.LogInformation(
            "Processed refund for group {GroupId}: {RefundAmount:C}. Model: {ModelId}, Reason: {RefundReason}, Previous Balance: {PreviousBalance:C}, New Balance: {NewBalance:C}, Transaction ID: {TransactionId}",
            virtualKeyGroupId,
            refundResult.RefundAmount,
            modelId,
            refundReason,
            previousBalance,
            group.Balance,
            transaction.Id);

        if (refundResult.ValidationMessages.Count > 0)
        {
            _logger.LogWarning(
                "Refund for group {GroupId} had validation warnings: {ValidationMessages}",
                virtualKeyGroupId,
                string.Join("; ", refundResult.ValidationMessages));
        }

        return refundResult;
    }
}
