using ConduitLLM.Core.Events;

namespace ConduitLLM.Tests.Core.Events
{
    /// <summary>
    /// Unit tests for ConnectionLimitExceeded domain event
    /// </summary>
    [Trait("Category", "Unit")]
    [Trait("Component", "ConnectionLimitExceeded")]
    [Trait("Feature", "ConnectionLimiting")]
    public class ConnectionLimitExceededTests
    {
        [Fact]
        public void Constructor_SetsDefaultValues()
        {
            // Arrange & Act
            var eventRecord = new ConnectionLimitExceeded();

            // Assert
            Assert.Equal(0, eventRecord.VirtualKeyId);
            Assert.Equal(string.Empty, eventRecord.VirtualKeyHash);
            Assert.Equal(0, eventRecord.CurrentConnections);
            Assert.Equal(0, eventRecord.MaxConnections);
            Assert.Null(eventRecord.HubName);
            Assert.Null(eventRecord.IpAddress);
        }

        [Fact]
        public void InheritsFromDomainEvent()
        {
            // Arrange & Act
            var eventRecord = new ConnectionLimitExceeded();

            // Assert
            Assert.IsAssignableFrom<DomainEvent>(eventRecord);
            Assert.IsAssignableFrom<IDomainEvent>(eventRecord);
        }

        [Fact]
        public void DomainEventProperties_AreAutoGenerated()
        {
            // Arrange & Act
            var eventRecord = new ConnectionLimitExceeded();

            // Assert
            Assert.NotNull(eventRecord.EventId);
            Assert.NotEmpty(eventRecord.EventId);
            Assert.True(Guid.TryParse(eventRecord.EventId, out _));
            Assert.True(eventRecord.Timestamp <= DateTime.UtcNow);
            Assert.True(eventRecord.Timestamp >= DateTime.UtcNow.AddSeconds(-1)); // Should be very recent
        }

        [Fact]
        public void EventId_IsUniqueForEachInstance()
        {
            // Arrange & Act
            var event1 = new ConnectionLimitExceeded();
            var event2 = new ConnectionLimitExceeded();

            // Assert
            Assert.NotEqual(event1.EventId, event2.EventId);
        }

        [Theory]
        [InlineData(0)]
        [InlineData(1)]
        [InlineData(123)]
        [InlineData(12345)]
        [InlineData(int.MaxValue)]
        public void PartitionKey_ReturnsVirtualKeyIdAsString(int virtualKeyId)
        {
            // Arrange & Act
            var eventRecord = new ConnectionLimitExceeded
            {
                VirtualKeyId = virtualKeyId
            };

            // Assert
            Assert.Equal(virtualKeyId.ToString(), eventRecord.PartitionKey);
        }

        [Fact]
        public void AllProperties_CanBeSetViaInitializer()
        {
            // Arrange
            const int virtualKeyId = 42;
            const string virtualKeyHash = "abc123hash";
            const int currentConnections = 99;
            const int maxConnections = 100;
            const string hubName = "MetricsHub";
            const string ipAddress = "192.168.1.100";
            const string correlationId = "corr-123";

            // Act
            var eventRecord = new ConnectionLimitExceeded
            {
                VirtualKeyId = virtualKeyId,
                VirtualKeyHash = virtualKeyHash,
                CurrentConnections = currentConnections,
                MaxConnections = maxConnections,
                HubName = hubName,
                IpAddress = ipAddress,
                CorrelationId = correlationId
            };

            // Assert
            Assert.Equal(virtualKeyId, eventRecord.VirtualKeyId);
            Assert.Equal(virtualKeyHash, eventRecord.VirtualKeyHash);
            Assert.Equal(currentConnections, eventRecord.CurrentConnections);
            Assert.Equal(maxConnections, eventRecord.MaxConnections);
            Assert.Equal(hubName, eventRecord.HubName);
            Assert.Equal(ipAddress, eventRecord.IpAddress);
            Assert.Equal(correlationId, eventRecord.CorrelationId);
        }

        [Fact]
        public void NullableProperties_CanBeNull()
        {
            // Arrange & Act
            var eventRecord = new ConnectionLimitExceeded
            {
                HubName = null,
                IpAddress = null
            };

            // Assert
            Assert.Null(eventRecord.HubName);
            Assert.Null(eventRecord.IpAddress);
        }

        [Fact]
        public void Record_SupportsEquality()
        {
            // Arrange - Records with same EventId should be equal
            var eventId = Guid.NewGuid().ToString();
            var timestamp = DateTime.UtcNow;

            var event1 = new ConnectionLimitExceeded
            {
                VirtualKeyId = 1,
                VirtualKeyHash = "hash",
                CurrentConnections = 100,
                MaxConnections = 100
            } with { EventId = eventId, Timestamp = timestamp };

            var event2 = new ConnectionLimitExceeded
            {
                VirtualKeyId = 1,
                VirtualKeyHash = "hash",
                CurrentConnections = 100,
                MaxConnections = 100
            } with { EventId = eventId, Timestamp = timestamp };

            // Assert
            Assert.Equal(event1, event2);
        }
    }
}
