#!/bin/bash
# Script to get the WebUI Internal Virtual Key

# First, ensure services are running
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$SCRIPT_DIR/wait-for-services.sh" || exit 1

# Get master key
MASTER_KEY=$("$SCRIPT_DIR/get-master-key.sh")
if [ $? -ne 0 ]; then
    echo "Error: Failed to get master key" >&2
    exit 1
fi

echo "Using master key: $MASTER_KEY" >&2

# Get all virtual keys from Admin API
RESPONSE=$(curl -s -X GET http://localhost:5002/api/virtualkeys \
  -H "X-Master-Key: $MASTER_KEY" \
  -H "Content-Type: application/json")

# Check if request was successful
if [ $? -ne 0 ] || [ -z "$RESPONSE" ]; then
    echo "Error: Failed to get virtual keys from Admin API" >&2
    exit 1
fi

# Check for error in response
if echo "$RESPONSE" | grep -q '"error"'; then
    echo "Error from API: $RESPONSE" >&2
    exit 1
fi

# Look for WebUI Internal Key (try both names)
WEBUI_KEY=$(echo "$RESPONSE" | jq -r '.[] | select(.keyName == "WebUI Internal Key (Fixed)") | .key // empty' 2>/dev/null)
if [ -z "$WEBUI_KEY" ]; then
    WEBUI_KEY=$(echo "$RESPONSE" | jq -r '.[] | select(.keyName == "WebUI Internal Key") | .key // empty' 2>/dev/null)
fi

if [ -z "$WEBUI_KEY" ]; then
    echo "WebUI Internal Key not found. Regenerating..." >&2

    # Find and delete any old WebUI keys that might exist
    # This includes "WebUI Internal Key", "WebUI Internal Key (Fixed)", and "WebUI Internal Key (Regenerated)"
    OLD_KEY_IDS=$(echo "$RESPONSE" | jq -r '.[] | select(.keyName | test("^WebUI Internal Key")) | .id' 2>/dev/null)

    for KEY_ID in $OLD_KEY_IDS; do
        echo "Deleting old WebUI key with ID: $KEY_ID" >&2
        curl -s -o /dev/null -X DELETE "http://localhost:5002/api/virtualkeys/$KEY_ID" \
          -H "X-Master-Key: $MASTER_KEY"
    done

    # Create a new key
    echo "Creating new 'WebUI Internal Key (Fixed)'..." >&2
    CREATE_PAYLOAD=$(cat <<EOF
{
    "keyName": "WebUI Internal Key (Fixed)",
    "allowedModels": null,
    "maxBudget": null,
    "budgetDuration": null,
    "expiresAt": null,
    "metadata": "{\"purpose\": \"Internal WebUI authentication, regenerated by get-webui-virtual-key.sh\"}",
    "rateLimitRpm": null,
    "rateLimitRpd": null
}
EOF
)
    
    CREATE_RESPONSE=$(curl -s -X POST http://localhost:5002/api/virtualkeys \
      -H "X-Master-Key: $MASTER_KEY" \
      -H "Content-Type: application/json" \
      -d "$CREATE_PAYLOAD")

    # Check for curl error or API error
    if [ $? -ne 0 ] || echo "$CREATE_RESPONSE" | grep -q '"error"'; then
        echo "Error: Failed to create new WebUI key. API response:" >&2
        echo "$CREATE_RESPONSE" >&2
        exit 1
    fi

    # Extract the new key
    WEBUI_KEY=$(echo "$CREATE_RESPONSE" | jq -r '.virtualKey // empty')

    if [ -z "$WEBUI_KEY" ]; then
        echo "Error: Failed to extract new key from API response." >&2
        echo "$CREATE_RESPONSE" >&2
        exit 1
    fi
    
    echo "Successfully regenerated WebUI key." >&2
fi

echo "$WEBUI_KEY"