<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Polly" />
    <PackageReference Include="prometheus-net" />
    <PackageReference Include="prometheus-net.AspNetCore" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="TiktokenSharp" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ConduitLLM.Configuration\ConduitLLM.Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ConduitLLM.Tests" />
  </ItemGroup>

</Project>
