name: Build and Publish Docker images

on:
  push:
    branches: ['master', 'dev']
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push WebUI Docker image
      - name: Build and push WebUI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ConduitLLM.WebUI
          file: ./ConduitLLM.WebUI/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-webui:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-webui:latest

      # Build and push Http Docker image
      - name: Build and push Http Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ConduitLLM.Http
          file: ./ConduitLLM.Http/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-http:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-http:latest
