name: Publish Docker image to GHCR

on:
  push:
    branches: ['master', 'dev'] # Trigger on pushes to the master and dev branches

permissions:
  contents: read
  packages: write # Needed to push to GHCR

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Uses owner/repo format like knnlabs/Conduit
          tags: |
            type=sha # Tag with the git commit SHA
            type=raw,value=latest,enable=${{ github.ref_name == 'master' }} # 'latest' only for master
            type=raw,value=master,enable=${{ github.ref_name == 'master' }} # 'master' tag only for master
            type=raw,value=dev,enable=${{ github.ref_name == 'dev' }} # 'dev' tag only for dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile # Explicitly specify the Dockerfile path
